name: 构建并发布应用

on:
  push:
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 获取版本号
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: 安装依赖
        run: pnpm install

      - name: 构建应用
        run: pnpm run make

      - name: 列出构建产物
        run: |
          ls -la out || echo "out目录不存在"
          find . -type d -name "out" | xargs ls -la
          find . -name "*.dmg" || echo "未找到dmg文件"
          find . -name "*.zip" || echo "未找到zip文件"
        shell: bash

      - name: 创建Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: 待办事项应用 ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./out/**/*.dmg
            ./out/**/*.zip
          body: |
            # 待办事项应用 ${{ github.ref_name }}

            ## 发布说明

            这是待办事项应用的最新版本。

            ## 下载

            - macOS: `.dmg` 或 `.zip`

            ## 更新日志

            请查看 [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) 获取详细信息。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}